- name: Install/Uninstall 'sip/sip3-hoof:{{version}}' container
  docker_container:
    name: sip3-hoof
    image: "sip3/sip3-hoof:{{version}}"
    networks:
      - name: sip3
        aliases:
          - sip3-hoof
    ports:
      - "{{port}}:80"
    restart: yes
    state: "{{state}}"