- name: Create/Delete '{{directory}}' directory
  file:
    path: "~/{{directory}}"
    mode: 0777
    state: directory

- name: Retrieve 'sip3-ansible' root directory
  find:
    path: "~"
    file_type: directory
    patterns: "{{directory}}"
  register: find_result

- name: Set 'sip3-ansible' {{root}} variable
  set_fact:
    root: '{{find_result.files[0].path}}'

- name: Create/Delete '{{root}}' directory
  file:
    path: "{{root}}"
    mode: 0777
    state: "{{state}}"

- name: Create/Delete '{{root}}/opt/sip3' directory
  file:
    path: "{{root}}/opt/sip3"
    mode: 0777
    state: "{{state}}"

- name: Create/Delete '{{root}}/opt/sip3/udf' directory
  file:
    path: "{{root}}/opt/sip3/udf"
    mode: 0777
    state: "{{state}}"

- name: Create/Delete '{{root}}/log/sip3' directory
  file:
    path: "{{root}}/log/sip3"
    mode: 0777
    state: "{{state}}"