- name: Copy sip3-twig configuration (application.yml)
  template:
    src: templates/application.yml.j2
    dest: "{{root}}/opt/sip3/twig.yml"
    mode: 0777
  when: state == 'started'

- name: Install/Uninstall 'sip/sip3-twig:{{version}}' container
  docker_container:
    name: sip3-twig
    image: "sip3/sip3-twig:{{version}}"
    networks:
      - name: sip3
        aliases:
          - sip3-twig
    volumes:
      - "{{root}}/log/sip3:/var/log/sip3-twig"
      - "{{root}}/opt/sip3:/opt/sip3"
    env:
      JAVA_OPTS: "-Xms128m -Xmx256m"
      CONFIG_FILE: "/opt/sip3/twig.yml"
    restart: yes
    state: "{{state}}"