- name: "Create SIP3 Twig configuration files"
  template:
    src: "{{ item.name }}.j2"
    dest: "/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "sip3"
    group: "sip3"
  loop:
    - { name: "etc/sip3-twig/application.yml", mode: "0644" }
    - { name: "etc/sip3-twig/environment.conf", mode: "0644" }
    - { name: "etc/sip3-twig/logback.xml", mode: "0644" }

- name: restart sip3-twig
  systemd:
    name: sip3-twig
    daemon_reload: true
    state: restarted
    enabled: true
  when: state == "started"
