# Before run the playbook, please check inventory file
# You should setup properties for correct installation
#
# To run playbook, please use:
# ansible-playbook -i inventories/inventory.yml playbooks/sip3.yml
#
# Also you can set tags which will be use: sip3, storage, frontend, backend
# E.g.
# ansible-playbook -i inventories/inventory.yml playbooks/sip3.yml -t storage
#
# tag sip3: will manipulate with sip3 components, such as SIP3 Captain, Salto, Twig, Hoof
# tag storage: will manipulate only with components MongoDB and InfluxDB
# tag frontend: will manipulate only with components SIP3 Hoof and Grafana
# tag backend: will manipulate with components, such as SIP3 Salto, Twig
#
# Also you set exclusion host.
# For example, you need run playbook without captain
# ansible-playbook -i inventories/inventory.yml playbooks/sip3.yml --limit 'all:!captain'

- name: "Deploy MongoDB"
  hosts: mongodb, backend
  roles:
    - role: ../roles/mongodb
      tags: storage

- name: "Deploy InfluxDB"
  hosts: influxdb, backend
  roles:
    - role: ../roles/influxdb
      tags: storage

- name: "Install OpenJDK"
  hosts: captain, salto, twig, backend
  roles:
    - role: ../roles/java
      tags: backend, sip3, salto, twig, captain

- name: "Install SIP3 Salto"
  hosts: salto, backend
  roles:
    - role: ../roles/salto
      tags: backend, sip3, salto

- name: "Install SIP3 Twig"
  hosts: twig, backend
  roles:
    - role: ../roles/twig
      tags: backend, sip3, twig

- name: "Install SIP3 Hoof"
  hosts: hoof, backend
  roles:
    - role: ../roles/hoof
      tags: frontend, sip3, hoof

- name: "Install Grafana"
  hosts: grafana, backend
  roles:
    - role: ../roles/grafana
      tags: frontend, grafana

- name: "Install SIP3 Captain"
  hosts: captain
  roles:
    - role: ../roles/captain
      tags: sip3, captain
